---
- name: Drop datasources provisioning file
  template:
    src: datasources-ansible.yml.j2
    dest: "{{ grafana_dir_home }}/{{ grafana_config.paths.provisioning }}/datasources/ansible.yml"
    owner: "{{ grafana_user }}"
    group: "{{ grafana_group }}"
    mode: 0644
  notify: Restart grafana server
  when:
    - grafana_datasources|length > 0
  tags:
    - grafana-datasource

- block: # Drop dashboard files
  - name: Drop dashboards json files
    copy:
      src: "{{ grafana_dashboard_json_path }}/"
      dest: "{{ grafana_dir_data }}/dashboards"
      owner: "{{ grafana_user }}"
      group: "{{ grafana_group }}"
    notify: Restart grafana server
    when:
      - grafana_dashboard_check is defined
      - grafana_dashboard_check.stat is defined
      - grafana_dashboard_check.stat.isdir is defined
      - grafana_dashboard_check.stat.isdir

  - name: Drop dashboards provisioning files
    template:
      src: dashboards-ansible.yml.j2
      dest: "{{ grafana_dir_home }}/{{ grafana_config.paths.provisioning }}/dashboards/ansible.yml"
      owner: "{{ grafana_user }}"
      group: "{{ grafana_group }}"
      mode: 0644
    notify: Restart grafana server
    when:
      - grafana_dashboard_providers|length > 0

  - meta: flush_handlers

  tags:
    - grafana-dashboard
