---
- block:
  - name: Add grafana repository key
    apt_key:
      url: "{{ grafana_apt_key_url }}"
      id: "{{ grafana_apt_key_id }}"

  - name: Add grafana apt-repository
    apt_repository:
      repo: "{{ grafana_apt_repo }}"
  when: ansible_pkg_mgr == "apt"
  
- block:
  - name: Add Grafana repository file from template [RHEL/CentOS]
    template:
      src: "{{ grafana_yum_repo_template }}"
      dest: "/etc/yum.repos.d/{{ grafana_yum_repo_template | basename | regex_replace('\\.j2$', '') }}"
      force: true
      backup: true

  - name: Copy Grafana GPG key
    template:
      src: "{{ grafana_gpg_key }}"
      dest: /etc/pki/rpm-gpg/
  when:
    - ansible_pkg_mgr in ['yum', 'dnf'] 
    - grafana_custom_repo